### ISSUE TITLE
unable to add evolver device

### ISSUE THREAD

**Issue by ezirayw** [ssec-jhu/evolver-ui#16]
When trying to add the evolver's instance url, I receive a popup indicating a "crypto undefined" error. I'm unsure if there was an issue while I built the application, but I did enter obviously wrong urls which report back errors indicating that an evolver is not found, making me think its a configuration setting problem.
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/cc7e2392-7ab2-4157-ab62-76cbaacfdcfe">

**Comment by imaitland** [comment]
when running the ui did you do this step from the readme?

```
mise use node@lts
```

This will ensure you're using a version of node that has the `crypto` api.

e.g.

<img width="558" alt="Screenshot 2024-12-09 at 11 14 23 AM" src="https://github.com/user-attachments/assets/cf9e4688-a05e-4ba7-9ef9-6c6a6fec959b">

**Comment by ezirayw** [comment]
Thanks. It was definitely my Nodejs version. I initially installed with apt, which gave v18. Installing v20 fixed the issue.
